apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: attach-ssl
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "static-ip"
    networking.gke.io/managed-certificates: certificate-for-domain
spec:
  backend:
    serviceName: backend-service
    servicePort: 80
